### ISSUE TITLE
includeLongLat Not Working

### ISSUE THREAD

**Issue by tmurphy821** [JobBrander/jobs-indeed#5]
Hey Karl/Steve,

When setting the API to includeLongLat the results I receive do not include any long/lat values. Is this due to indeed simply not having this information so not retrieving or is this broken? I've attached examples of my request/results. 

![image](https://cloud.githubusercontent.com/assets/18452898/14546971/403134e4-025e-11e6-88c8-ccb8b9b4ed52.png)

![image](https://cloud.githubusercontent.com/assets/18452898/14546976/529232e6-025e-11e6-94c2-d649b26cc467.png)

Thanks,

-Tim

**Comment by tmurphy821** [comment]
I'm using php/json but looking at the xml example on the publisher API documentation it looks like this information is available. This example even has Zipcode! Any way to get zipcode via json request?

![image](https://cloud.githubusercontent.com/assets/18452898/14547114/61312806-025f-11e6-98fe-f59c89fa822a.png)

**Comment by karllhughes** [comment]
@tmurphy821 it looks like you are correct that when you add `includeLatLong(1)` to your query and then look at the results from this package, the Latitude and Longitude are not attached to the JobLocation Place object as you might expect.

This ends up being rather complex unfortunately as Schema.org's [Place](https://schema.org/Place) object doesn't include those attributes directly (although it [looks like someone wants to do just that](https://github.com/schemaorg/schemaorg/issues/1082)), but includes another object called [GeoCoordinates](https://schema.org/GeoCoordinates) that includes latitude and longitude. We currently don't support this GeoCoordinates object.

It looks like in order for us to support latitude and longitude while remaining consistent with Schema.org's specifications, we'll need to support this GeoCoordinates object in the jobs common project.

I'm going to add another issue to look into updating the jobs-common project to add this attribute. It likely won't get in until we do a version 2 launch later this summer though, so in the meantime, I'd suggest finding a workaround :-/

**Comment by karllhughes** [comment]
I've included this in the branch to be released with jobs common v.2 this summer as well.
