### ISSUE TITLE
Include Zip code in response when possible

### ISSUE THREAD

**Issue by karllhughes** [JobBrander/jobs-indeed#6]
I got this email from @tmurphy821 over the weekend so I'm going to look into this as well as #5 

Is it possible to get zipcodes from Indeed? I see their xml/json requests come back with them but the query through jobbrander doesn't include the zipcodes.

example: `http://api.indeed.com/ads/apisearch?publisher=<PUB_ID>&q=barista&format=json&l=boulder%2C+co&sort=&radius=10&st=&jt=&start=&limit=&fromage=&filter=&latlong=1&co=us&chnl=&userip=1.2.3.4&useragent=Mozilla/%2F4.0%28Firefox%29&v=2`

**Comment by karllhughes** [comment]
It looks like this can be done. I'm going to work on adding a zip code parser for the Indeed client in my v.2 branch. Should be available this summer sometime.

**Comment by karllhughes** [comment]
Added this in the v1 branch.

**Comment by tmurphy821** [comment]
Hey Karl,

Just confirming your above comment. By "added to v1 branch" did you implement this over the weekend? Or will this come out with v2 in the summer.

Thanks!

-Tim

**Comment by karllhughes** [comment]
Yeah sorry for the confusion @tmurphy821 I've added it to the branch that will get released this summer along with other improvements to the core jobs-common package. I'll be sure to reach out when the new version is complete to get your take on it.
